version: '2'
services:
  db:
    image: postgres
  web:
    build: ./web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  redis:
    image: redis
  async_shipyard:
    build: ./web
    command: python manage.py shipyard_async
    depends_on:
      - db
      - redis