# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import ui.models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0005_ship_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ship',
            name='planet',
            field=models.ForeignKey(on_delete=models.SET(ui.models.get_default_ship_location), related_name='orbiters', to='ui.Planet'),
        ),
    ]
