# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 21:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0008_auto_20170219_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='fuel_markup',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='ship',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='ui.Profile'),
        ),
    ]
