# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import ui.models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0009_auto_20170219_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='home_planet',
            field=models.ForeignKey(default=599, on_delete=models.SET(ui.models.get_default_ship_location), related_name='registrants', to='ui.Planet'),
            preserve_default=False,
        ),
    ]
