# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0010_ship_home_planet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('total_value', models.FloatField(default=0.0)),
                ('ship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargo', to='ui.Ship')),
            ],
        ),
    ]
