# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0011_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipUpgrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=10)),
                ('target', models.CharField(default='cargo', max_length=100)),
                ('cost', models.IntegerField(default=100000)),
            ],
        ),
        migrations.AddField(
            model_name='ship',
            name='cargo_capactiy_max',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='shipupgrade',
            name='ship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='ui.Ship'),
        ),
    ]
