# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0013_auto_20170422_2045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipupgrade',
            old_name='space',
            new_name='capacity',
        ),
        migrations.AddField(
            model_name='shipupgrade',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
