# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0014_auto_20170423_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipYard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipyards', to='ui.Planet')),
            ],
        ),
    ]
