# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 15:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0015_shipyard'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipupgrade',
            name='shipyard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='upgrades', to='ui.ShipYard'),
        ),
    ]
