# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0016_shipupgrade_shipyard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ship',
            name='upgrade_capactiy_max',
        ),
    ]
