# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 18:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import ui.models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0018_ship_shipyard'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='computer',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=ui.models.default_ship_computer),
        ),
    ]
