# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0019_ship_computer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipupgrade',
            name='cost',
            field=models.BigIntegerField(default=100000),
        ),
    ]
