# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 19:52
from __future__ import unicode_literals

from django.db import migrations
from ui.models import default_ship_computer


def seed_cargo_in_ships_computer(apps, schema_editor):
    Ship =  apps.get_model("ui", "Ship")
    updated = 0

    for ship in Ship.objects.all():
        comp = ship.computer
        comp["limits"]["cargo"] = {"history":5}
        comp["cargo"] = {"history":[]}
        ship.computer = comp
        ship.save()
        updated +=1
    #print "%d Ship::computer records updated with cargo tracking" % (updated,)

class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0020_auto_20170514_1907'),
    ]

    operations = [
        migrations.RunPython(seed_cargo_in_ships_computer)
    ]
