# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-10 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0022_auto_20170610_1957'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Planet',
            new_name='Location',
        ),
    ]
