# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0023_auto_20170610_2005'),
    ]

    operations = [
        migrations.RenameField('Ship', 'planet', 'location')
    ]
