# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0025_auto_20170612_0100'),
    ]

    operations = [
        migrations.RenameField('Ship', 'home_planet', 'home_location')
    ]
