# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 02:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0026_auto_20170612_0214'),
    ]

    operations = [
        migrations.RenameField('Good', 'planet', 'location')
    ]
