# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-12 02:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0027_auto_20170612_0219'),
    ]

    operations = [
        migrations.RenameField('ShipYard', 'planet', 'location')
    ]
