# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 21:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0028_auto_20170612_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ui.Location'),
        ),
    ]
